name: Publish Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]  # Opcional: publica también cuando creas tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Permiso esencial para publicar en GHCR
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Se usa automáticamente

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
